export const missionsData = [
  {
    category: "Animals",
    items: [
      { id: 1, name: "DOG", image: require("../assets/assets/dog.jpg") },
      { id: 2, name: "CAT", image: require("../assets/assets/cat.jpg") },
      { id: 3, name: "FROG", image: require("../assets/assets/frog.jpg") },
      { id: 4, name: "LION", image: require("../assets/assets/lion.jpg") },
      { id: 5, name: "BEAR", image: require("../assets/assets/bear.jpg") },
      { id: 6, name: "HORSE", image: require("../assets/assets/horse.jpg") },
      { id: 7, name: "EAGLE", image: require("../assets/assets/eagle.jpg") },
      { id: 8, name: "RABBIT", image: require("../assets/assets/rabbit.jpg") },
      { id: 9, name: "WOLF", image: require("../assets/assets/wolf.jpg") },
      { id: 10, name: "KANGAROO", image: require("../assets/assets/kangaroo.jpg") },
      { id: 11, name: "PENGUIN", image: require("../assets/assets/penguin.jpg") },
      { id: 12, name: "CROCODILE", image: require("../assets/assets/crocodile.jpg") },
      { id: 13, name: "CHAMELEON", image: require("../assets/assets/chameleon.jpg") },
      { id: 14, name: "HIPPOPOTAMUS", image: require("../assets/assets/hippo.jpg") },
      { id: 15, name: "PORCUPINE", image: require("../assets/assets/porcupine.jpg") },
      { id: 16, name: "RHINOCEROS", image: require("../assets/assets/rhino.jpg") },
      { id: 17, name: "FLAMINGO", image: require("../assets/assets/flamingo.jpg") },
      { id: 18, name: "HEDGEHOG", image: require("../assets/assets/hedgehog.jpg") },
      { id: 19, name: "WOODPECKER", image: require("../assets/assets/woodpecker.jpg") },
      { id: 20, name: "HIPPOGRIFF", image: require("../assets/assets/hippogriff.jpg") },
      { id: 21, name: "TIGER", image: require("../assets/assets/tiger.jpg") },
      { id: 22, name: "ELEPHANT", image: require("../assets/assets/elephant.jpg") },
      { id: 23, name: "GIRAFFE", image: require("../assets/assets/giraffe.jpg") },
      { id: 24, name: "ZEBRA", image: require("../assets/assets/zebra.jpg") },
      { id: 25, name: "PANDA", image: require("../assets/assets/panda.jpg") },
      { id: 26, name: "CHEETAH", image: require("../assets/assets/cheetah.jpg") },
      { id: 27, name: "OWL", image: require("../assets/assets/owl.jpg") },
      { id: 28, name: "PARROT", image: require("../assets/assets/parrot.jpg") },
      { id: 29, name: "SNAKE", image: require("../assets/assets/snake.jpg") },
      { id: 30, name: "TURTLE", image: require("../assets/assets/turtle.jpg") },
      { id: 31, name: "DOLPHIN", image: require("../assets/assets/dolphin.jpg") },
      { id: 32, name: "SHARK", image: require("../assets/assets/shark.jpg") },
      { id: 33, name: "WHALE", image: require("../assets/assets/whale.jpg") },
      { id: 34, name: "FOX", image: require("../assets/assets/fox.jpg") },
      { id: 35, name: "DEER", image: require("../assets/assets/deer.jpg") },
      { id: 36, name: "CAMEL", image: require("../assets/assets/camel.jpg") },
      { id: 37, name: "OSTRICH", image: require("../assets/assets/ostrich.jpg") },
      { id: 38, name: "PEACOCK", image: require("../assets/assets/peacock.jpg") },
      { id: 39, name: "GORILLA", image: require("../assets/assets/gorilla.jpg") },
      { id: 40, name: "LEOPARD", image: require("../assets/assets/leopard.jpg") }
    ]
  },
  {
    category: "Technology",
    items: [
      { id: 21, name: "PHONE", image: require("../assets/assets/phone.jpg") },
      { id: 22, name: "LAPTOP", image: require("../assets/assets/laptop.jpg") },
      { id: 23, name: "TABLET", image: require("../assets/assets/tablet.jpg") },
      { id: 24, name: "ROBOT", image: require("../assets/assets/robot.jpg") },
      { id: 25, name: "CAMERA", image: require("../assets/assets/camera.jpg") },
      { id: 26, name: "DRONE", image: require("../assets/assets/drone.jpg") },
      { id: 27, name: "PRINTER", image: require("../assets/assets/printer.jpg") },
      { id: 28, name: "MICROWAVE", image: require("../assets/assets/microwave.jpg") },
      { id: 29, name: "SPEAKER", image: require("../assets/assets/speaker.jpg") },
      { id: 210, name: "MONITOR", image: require("../assets/assets/monitor.jpg") },
      { id: 211, name: "HEADPHONES", image: require("../assets/assets/headphones.jpg") },
      { id: 212, name: "SMARTWATCH", image: require("../assets/assets/watch.jpg") },
      { id: 213, name: "PROJECTOR", image: require("../assets/assets/projector.jpg") },
      { id: 214, name: "TELEVISION", image: require("../assets/assets/tv.jpg") },
      { id: 215, name: "JOYSTICK", image: require("../assets/assets/joystick.jpg") },
      { id: 216, name: "SATELLITE", image: require("../assets/assets/satellite.jpg") },
      { id: 217, name: "MICROCHIP", image: require("../assets/assets/chip.jpg") },
      { id: 218, name: "CIRCUIT", image: require("../assets/assets/circuit.jpg") },
      { id: 219, name: "NANOTECH", image: require("../assets/assets/nano.jpg") },
      { id: 220, name: "QUANTUMCOMPUTER", image: require("../assets/assets/quantum.jpg") },
      { id: 221, name: "KEYBOARD", image: require("../assets/assets/keyboard.jpg") },
      { id: 222, name: "MOUSE", image: require("../assets/assets/mouse.jpg") },
      { id: 223, name: "WEBCAM", image: require("../assets/assets/webcam.jpg") },
      { id: 224, name: "SERVER", image: require("../assets/assets/server.jpg") },
      { id: 225, name: "ROUTER", image: require("../assets/assets/router.jpg") },
      { id: 226, name: "VRHEADSET", image: require("../assets/assets/vrheadset.jpg") },
      { id: 227, name: "SMARTGLASSES", image: require("../assets/assets/smartglasses.jpg") },
      { id: 228, name: "EXOSKELETON", image: require("../assets/assets/exoskeleton.jpg") },
      { id: 229, name: "GPS", image: require("../assets/assets/gps.jpg") },
      { id: 230, name: "SMARTLOCK", image: require("../assets/assets/smartlock.jpg") },
      { id: 231, name: "FINGERPRINTSCANNER", image: require("../assets/assets/fingerprintscanner.jpg") },
      { id: 232, name: "HOLOGRAM", image: require("../assets/assets/hologram.jpg") },
      { id: 233, name: "BATTERY", image: require("../assets/assets/battery.jpg") },
      { id: 234, name: "SOLARPANEL", image: require("../assets/assets/solarpanel.jpg") },
      { id: 235, name: "MEMORYCARD", image: require("../assets/assets/memorycard.jpg") },
      { id: 236, name: "USBDRIVE", image: require("../assets/assets/usbdrive.jpg") },
      { id: 237, name: "SMARTTHERMOSTAT", image: require("../assets/assets/smartthermostat.jpg") },
      { id: 238, name: "EBOOKREADER", image: require("../assets/assets/ebookreader.jpg") },
      { id: 239, name: "WEARABLETRACKER", image: require("../assets/assets/wearabletracker.jpg") },
      { id: 240, name: "MICROPHONE", image: require("../assets/assets/microphone.jpg") }
    ]
  },
  {
    category: "Kitchen Items",
    items: [
      { id: 31, name: "FORK", image: require("../assets/assets/fork.jpg") },
      { id: 32, name: "SPOON", image: require("../assets/assets/spoon.jpg") },
      { id: 33, name: "KNIFE", image: require("../assets/assets/knife.jpg") },
      { id: 34, name: "PLATE", image: require("../assets/assets/plate.jpg") },
      { id: 35, name: "CUP", image: require("../assets/assets/cup.jpg") },
      { id: 36, name: "BOWL", image: require("../assets/assets/bowl.jpg") },
      { id: 37, name: "POT", image: require("../assets/assets/pot.jpg") },
      { id: 38, name: "PAN", image: require("../assets/assets/pan.jpg") },
      { id: 39, name: "KETTLE", image: require("../assets/assets/kettle.jpg") },
      { id: 310, name: "BLENDER", image: require("../assets/assets/blender.jpg") },
      { id: 311, name: "TOASTER", image: require("../assets/assets/toaster.jpg") },
      { id: 312, name: "GRATER", image: require("../assets/assets/grater.jpg") },
      { id: 313, name: "STRAINER", image: require("../assets/assets/strainer.jpg") },
      { id: 314, name: "WHISK", image: require("../assets/assets/whisk.jpg") },
      { id: 315, name: "CUTTINGBOARD", image: require("../assets/assets/cuttingboard.jpg") },
      { id: 316, name: "MEASURINGCUP", image: require("../assets/assets/measuringcup.jpg") },
      { id: 317, name: "ROLLINGPIN", image: require("../assets/assets/rollingpin.jpg") },
      { id: 318, name: "MICROWAVE", image: require("../assets/assets/microwave.jpg") },
      { id: 319, name: "DISHWASHER", image: require("../assets/assets/dishwasher.jpg") },
      { id: 320, name: "PRESSURECOOKER", image: require("../assets/assets/pressurecooker.jpg") },
      { id: 321, name: "SPATULA", image: require("../assets/assets/spatula.jpg") },
      { id: 322, name: "LADLE", image: require("../assets/assets/ladle.jpg") },
      { id: 323, name: "TONGS", image: require("../assets/assets/tongs.jpg") },
      { id: 324, name: "PEELER", image: require("../assets/assets/peeler.jpg") },
      { id: 325, name: "CANOPENER", image: require("../assets/assets/canopener.jpg") },
      { id: 326, name: "MIXINGBOWL", image: require("../assets/assets/mixingbowl.jpg") },
      { id: 327, name: "SIEVE", image: require("../assets/assets/sieve.jpg") },
      { id: 328, name: "OVENMITT", image: require("../assets/assets/ovenmitt.jpg") },
      { id: 329, name: "APRON", image: require("../assets/assets/apron.jpg") },
      { id: 330, name: "COFFEEMAKER", image: require("../assets/assets/coffeemaker.jpg") },
      { id: 331, name: "TEAPOT", image: require("../assets/assets/teapot.jpg") },
      { id: 332, name: "BAKINGTRAY", image: require("../assets/assets/bakingtray.jpg") },
      { id: 333, name: "MUFFINTIN", image: require("../assets/assets/muffintin.jpg") },
      { id: 334, name: "MEATGRINDER", image: require("../assets/assets/meatgrinder.jpg") },
      { id: 335, name: "FOODPROCESSOR", image: require("../assets/assets/foodprocessor.jpg") },
      { id: 336, name: "WOK", image: require("../assets/assets/wok.jpg") },
      { id: 337, name: "SKILLET", image: require("../assets/assets/skillet.jpg") },
      { id: 338, name: "MORTAR", image: require("../assets/assets/mortar.jpg") },
      { id: 339, name: "JUICER", image: require("../assets/assets/juicer.jpg") },
      { id: 340, name: "KITCHENSCALE", image: require("../assets/assets/kitchenscale.jpg") }
    ]
  },
  {
    category: "Fruits",
    items: [
      { id: 41, name: "APPLE", image: require("../assets/assets/apple.jpg") },
      { id: 42, name: "PEAR", image: require("../assets/assets/pear.jpg") },
      { id: 43, name: "BANANA", image: require("../assets/assets/banana.jpg") },
      { id: 44, name: "ORANGE", image: require("../assets/assets/orange.jpg") },
      { id: 45, name: "KIWI", image: require("../assets/assets/kiwi.jpg") },
      { id: 46, name: "GRAPE", image: require("../assets/assets/grape.jpg") },
      { id: 47, name: "MANGO", image: require("../assets/assets/mango.jpg") },
      { id: 48, name: "CHERRY", image: require("../assets/assets/cherry.jpg") },
      { id: 49, name: "PLUM", image: require("../assets/assets/plum.jpg") },
      { id: 410, name: "LEMON", image: require("../assets/assets/lemon.jpg") },
      { id: 411, name: "LIME", image: require("../assets/assets/lime.jpg") },
      { id: 412, name: "FIG", image: require("../assets/assets/fig.jpg") },
      { id: 413, name: "COCONUT", image: require("../assets/assets/coconut.jpg") },
      { id: 414, name: "PAPAYA", image: require("../assets/assets/papaya.jpg") },
      { id: 415, name: "PINEAPPLE", image: require("../assets/assets/pineapple.jpg") },
      { id: 416, name: "WATERMELON", image: require("../assets/assets/watermelon.jpg") },
      { id: 417, name: "STRAWBERRY", image: require("../assets/assets/strawberry.jpg") },
      { id: 418, name: "BLUEBERRY", image: require("../assets/assets/blueberry.jpg") },
      { id: 419, name: "BLACKBERRY", image: require("../assets/assets/blackberry.jpg") },
      { id: 420, name: "POMEGRANATE", image: require("../assets/assets/pomegranate.jpg") },
      { id: 421, name: "PEACH", image: require("../assets/assets/peach.jpg") },
      { id: 422, name: "APRICOT", image: require("../assets/assets/apricot.jpg") },
      { id: 423, name: "GRAPEFRUIT", image: require("../assets/assets/grapefruit.jpg") },
      { id: 424, name: "MELON", image: require("../assets/assets/melon.jpg") },
      { id: 425, name: "TANGERINE", image: require("../assets/assets/tangerine.jpg") },
      { id: 426, name: "GUAVA", image: require("../assets/assets/guava.jpg") },
      { id: 427, name: "DRAGONFRUIT", image: require("../assets/assets/dragonfruit.jpg") },
      { id: 428, name: "PASSIONFRUIT", image: require("../assets/assets/passionfruit.jpg") },
      { id: 429, name: "PERSIMMON", image: require("../assets/assets/persimmon.jpg") },
      { id: 430, name: "LYCHEE", image: require("../assets/assets/lychee.jpg") },
      { id: 431, name: "STARFRUIT", image: require("../assets/assets/starfruit.jpg") },
      { id: 432, name: "CLEMENTINE", image: require("../assets/assets/clementine.jpg") },
      { id: 433, name: "KUMQUAT", image: require("../assets/assets/kumquat.jpg") },
      { id: 434, name: "DURIAN", image: require("../assets/assets/durian.jpg") },
      { id: 435, name: "RAMBUTAN", image: require("../assets/assets/rambutan.jpg") },
      { id: 436, name: "JACKFRUIT", image: require("../assets/assets/jackfruit.jpg") },
      { id: 437, name: "CRANBERRY", image: require("../assets/assets/cranberry.jpg") },
      { id: 438, name: "GOOSEBERRY", image: require("../assets/assets/gooseberry.jpg") },
      { id: 439, name: "ELDERBERRY", image: require("../assets/assets/elderberry.jpg") },
      { id: 440, name: "SOURSOP", image: require("../assets/assets/soursop.jpg") }
    ]
  },
  {
    category: "Countries",
    items: [
      { id: 51, name: "USA", image: require("../assets/assets/usa.jpg") },
      { id: 52, name: "FRANCE", image: require("../assets/assets/france.jpg") },
      { id: 53, name: "JAPAN", image: require("../assets/assets/japan.jpg") },
      { id: 54, name: "BRAZIL", image: require("../assets/assets/brazil.jpg") },
      { id: 55, name: "INDIA", image: require("../assets/assets/india.jpg") },
      { id: 56, name: "ITALY", image: require("../assets/assets/italy.jpg") },
      { id: 57, name: "CANADA", image: require("../assets/assets/canada.jpg") },
      { id: 58, name: "SPAIN", image: require("../assets/assets/spain.jpg") },
      { id: 59, name: "GERMANY", image: require("../assets/assets/germany.jpg") },
      { id: 510, name: "RUSSIA", image: require("../assets/assets/russia.jpg") },
      { id: 511, name: "MEXICO", image: require("../assets/assets/mexico.jpg") },
      { id: 512, name: "CHINA", image: require("../assets/assets/china.jpg") },
      { id: 513, name: "EGYPT", image: require("../assets/assets/egypt.jpg") },
      { id: 514, name: "NIGERIA", image: require("../assets/assets/nigeria.jpg") },
      { id: 515, name: "NORWAY", image: require("../assets/assets/norway.jpg") },
      { id: 516, name: "ARGENTINA", image: require("../assets/assets/argentina.jpg") },
      { id: 517, name: "TURKEY", image: require("../assets/assets/turkey.jpg") },
      { id: 518, name: "POLAND", image: require("../assets/assets/poland.jpg") },
      { id: 519, name: "PORTUGAL", image: require("../assets/assets/portugal.jpg") },
      { id: 520, name: "AUSTRALIA", image: require("../assets/assets/australia.jpg") },
      { id: 521, name: "SOUTHKOREA", image: require("../assets/assets/southkorea.jpg") },
      { id: 522, name: "UKRAINE", image: require("../assets/assets/ukraine.jpg") },
      { id: 523, name: "THAILAND", image: require("../assets/assets/thailand.jpg") },
      { id: 524, name: "SOUTHAFRICA", image: require("../assets/assets/southafrica.jpg") },
      { id: 525, name: "SWEDEN", image: require("../assets/assets/sweden.jpg") },
      { id: 526, name: "VIETNAM", image: require("../assets/assets/vietnam.jpg") },
      { id: 527, name: "COLOMBIA", image: require("../assets/assets/colombia.jpg") },
      { id: 528, name: "IRELAND", image: require("../assets/assets/ireland.jpg") },
      { id: 529, name: "NEWZEALAND", image: require("../assets/assets/newzealand.jpg") },
      { id: 530, name: "GREECE", image: require("../assets/assets/greece.jpg") },
      { id: 531, name: "CHILE", image: require("../assets/assets/chile.jpg") },
      { id: 532, name: "PHILIPPINES", image: require("../assets/assets/philippines.jpg") },
      { id: 533, name: "SINGAPORE", image: require("../assets/assets/singapore.jpg") },
      { id: 534, name: "PERU", image: require("../assets/assets/peru.jpg") },
      { id: 535, name: "FINLAND", image: require("../assets/assets/finland.jpg") },
      { id: 536, name: "SWITZERLAND", image: require("../assets/assets/switzerland.jpg") },
      { id: 537, name: "PAKISTAN", image: require("../assets/assets/pakistan.jpg") },
      { id: 538, name: "DENMARK", image: require("../assets/assets/denmark.jpg") },
      { id: 539, name: "KENYA", image: require("../assets/assets/kenya.jpg") },
      { id: 540, name: "NETHERLANDS", image: require("../assets/assets/netherlands.jpg") }
    ]
  },
  {
    category: "Sports",
    items: [
      { id: 61, name: "SOCCER", image: require("../assets/assets/soccer.jpg") },
      { id: 62, name: "BASKETBALL", image: require("../assets/assets/basketball.jpg") },
      { id: 63, name: "TENNIS", image: require("../assets/assets/tennis.jpg") },
      { id: 64, name: "CRICKET", image: require("../assets/assets/cricket.jpg") },
      { id: 65, name: "BASEBALL", image: require("../assets/assets/baseball.jpg") },
      { id: 66, name: "RUGBY", image: require("../assets/assets/rugby.jpg") },
      { id: 67, name: "SWIMMING", image: require("../assets/assets/swimming.jpg") },
      { id: 68, name: "BOXING", image: require("../assets/assets/boxing.jpg") },
      { id: 69, name: "VOLLEYBALL", image: require("../assets/assets/volleyball.jpg") },
      { id: 610, name: "GOLF", image: require("../assets/assets/golf.jpg") },
      { id: 611, name: "HOCKEY", image: require("../assets/assets/hockey.jpg") },
      { id: 612, name: "ARCHERY", image: require("../assets/assets/archery.jpg") },
      { id: 613, name: "FENCING", image: require("../assets/assets/fencing.jpg") },
      { id: 614, name: "SKIING", image: require("../assets/assets/skiing.jpg") },
      { id: 615, name: "SURFING", image: require("../assets/assets/surfing.jpg") },
      { id: 616, name: "CYCLING", image: require("../assets/assets/cycling.jpg") },
      { id: 617, name: "SKATEBOARD", image: require("../assets/assets/skateboard.jpg") },
      { id: 618, name: "WEIGHTLIFTING", image: require("../assets/assets/weightlifting.jpg") },
      { id: 619, name: "TAEKWONDO", image: require("../assets/assets/taekwondo.jpg") },
      { id: 620, name: "MARTIALARTS", image: require("../assets/assets/martialarts.jpg") },
      { id: 621, name: "WRESTLING", image: require("../assets/assets/wrestling.jpg") },
      { id: 622, name: "BADMINTON", image: require("../assets/assets/badminton.jpg") },
      { id: 623, name: "TABLETENNIS", image: require("../assets/assets/tabletennis.jpg") },
      { id: 624, name: "GYMNASTICS", image: require("../assets/assets/gymnastics.jpg") },
      { id: 625, name: "DIVING", image: require("../assets/assets/diving.jpg") },
      { id: 626, name: "JUDO", image: require("../assets/assets/judo.jpg") },
      { id: 627, name: "KARATE", image: require("../assets/assets/karate.jpg") },
      { id: 628, name: "SHOOTING", image: require("../assets/assets/shooting.jpg") },
      { id: 629, name: "ROWING", image: require("../assets/assets/rowing.jpg") },
      { id: 630, name: "SAILING", image: require("../assets/assets/sailing.jpg") },
      { id: 631, name: "CLIMBING", image: require("../assets/assets/climbing.jpg") },
      { id: 632, name: "SNOWBOARDING", image: require("../assets/assets/snowboarding.jpg") },
      { id: 633, name: "TRIATHLON", image: require("../assets/assets/triathlon.jpg") },
      { id: 634, name: "POLO", image: require("../assets/assets/polo.jpg") },
      { id: 635, name: "HORSEBACKRIDING", image: require("../assets/assets/horsebackriding.jpg") },
      { id: 636, name: "CANOING", image: require("../assets/assets/canoing.jpg") },
      { id: 637, name: "KAYAKING", image: require("../assets/assets/kayaking.jpg") },
      { id: 638, name: "SYNCHRONIZEDSWIMMING", image: require("../assets/assets/synchronizedswimming.jpg") },
      { id: 639, name: "BMX", image: require("../assets/assets/bmx.jpg") },
      { id: 640, name: "PARAGLIDING", image: require("../assets/assets/paragliding.jpg") }
    ]
  },
  {
    category: "Transportation",
    items: [
      { id: 71, name: "CAR", image: require("../assets/assets/car.jpg") },
      { id: 72, name: "BIKE", image: require("../assets/assets/bike.jpg") },
      { id: 73, name: "BUS", image: require("../assets/assets/bus.jpg") },
      { id: 74, name: "TRAIN", image: require("../assets/assets/train.jpg") },
      { id: 75, name: "SHIP", image: require("../assets/assets/ship.jpg") },
      { id: 76, name: "PLANE", image: require("../assets/assets/plane.jpg") },
      { id: 77, name: "SUBWAY", image: require("../assets/assets/subway.jpg") },
      { id: 78, name: "HELICOPTER", image: require("../assets/assets/helicopter.jpg") },
      { id: 79, name: "SCOOTER", image: require("../assets/assets/scooter.jpg") },
      { id: 710, name: "BALLOON", image: require("../assets/assets/balloon.jpg") },
      { id: 711, name: "TRACTOR", image: require("../assets/assets/tractor.jpg") },
      { id: 712, name: "AMBULANCE", image: require("../assets/assets/ambulance.jpg") },
      { id: 713, name: "FIRETRUCK", image: require("../assets/assets/firetruck.jpg") },
      { id: 714, name: "ROCKET", image: require("../assets/assets/rocket.jpg") },
      { id: 715, name: "CABLECAR", image: require("../assets/assets/cablecar.jpg") },
      { id: 716, name: "FERRY", image: require("../assets/assets/ferry.jpg") },
      { id: 717, name: "YACHT", image: require("../assets/assets/yacht.jpg") },
      { id: 718, name: "SPACECRAFT", image: require("../assets/assets/spacecraft.jpg") },
      { id: 719, name: "MONORAIL", image: require("../assets/assets/monorail.jpg") },
      { id: 720, name: "DIRIGIBLE", image: require("../assets/assets/dirigible.jpg") },
      { id: 721, name: "TRUCK", image: require("../assets/assets/truck.jpg") },
      { id: 722, name: "MOTORBIKE", image: require("../assets/assets/motorbike.jpg") },
      { id: 723, name: "TAXI", image: require("../assets/assets/taxi.jpg") },
      { id: 724, name: "TRAM", image: require("../assets/assets/tram.jpg") },
      { id: 725, name: "SUBMARINE", image: require("../assets/assets/submarine.jpg") },
      { id: 726, name: "HOVERCRAFT", image: require("../assets/assets/hovercraft.jpg") },
      { id: 727, name: "JETSKI", image: require("../assets/assets/jetski.jpg") },
      { id: 728, name: "SEGWAY", image: require("../assets/assets/segway.jpg") },
      { id: 729, name: "GLIDER", image: require("../assets/assets/glider.jpg") },
      { id: 730, name: "CARRIAGE", image: require("../assets/assets/carriage.jpg") },
      { id: 731, name: "TROLLEYBUS", image: require("../assets/assets/trolleybus.jpg") },
      { id: 732, name: "SNOWMOBILE", image: require("../assets/assets/snowmobile.jpg") },
      { id: 733, name: "ATV", image: require("../assets/assets/atv.jpg") },
      { id: 734, name: "BULDOZER", image: require("../assets/assets/buldozer.jpg") },
      { id: 735, name: "CRANE", image: require("../assets/assets/crane.jpg") },
      { id: 736, name: "FORKLIFT", image: require("../assets/assets/forklift.jpg") },
      { id: 737, name: "HANGGLIDER", image: require("../assets/assets/hangglider.jpg") },
      { id: 738, name: "RICKSHAW", image: require("../assets/assets/rickshaw.jpg") },
      { id: 739, name: "PARACHUTE", image: require("../assets/assets/parachute.jpg") },
      { id: 740, name: "HOVERBOARD", image: require("../assets/assets/hoverboard.jpg") }
    ]
  },
  {
    category: "Professions",
    items: [
      { id: 81, name: "DOCTOR", image: require("../assets/assets/doctor.jpg") },
      { id: 82, name: "TEACHER", image: require("../assets/assets/teacher.jpg") },
      { id: 83, name: "FARMER", image: require("../assets/assets/farmer.jpg") },
      { id: 84, name: "CHEF", image: require("../assets/assets/chef.jpg") },
      { id: 85, name: "POLICE", image: require("../assets/assets/police.jpg") },
      { id: 86, name: "FIREFIGHTER", image: require("../assets/assets/firefighter.jpg") },
      { id: 87, name: "ENGINEER", image: require("../assets/assets/engineer.jpg") },
      { id: 88, name: "SCIENTIST", image: require("../assets/assets/scientist.jpg") },
      { id: 89, name: "ACTOR", image: require("../assets/assets/actor.jpg") },
      { id: 810, name: "LAWYER", image: require("../assets/assets/lawyer.jpg") },
      { id: 811, name: "NURSE", image: require("../assets/assets/nurse.jpg") },
      { id: 812, name: "MECHANIC", image: require("../assets/assets/mechanic.jpg") },
      { id: 813, name: "PILOT", image: require("../assets/assets/pilot.jpg") },
      { id: 814, name: "ARTIST", image: require("../assets/assets/artist.jpg") },
      { id: 815, name: "PHOTOGRAPHER", image: require("../assets/assets/photographer.jpg") },
      { id: 816, name: "DENTIST", image: require("../assets/assets/dentist.jpg") },
      { id: 817, name: "PROGRAMMER", image: require("../assets/assets/programmer.jpg") },
      { id: 818, name: "ARCHITECT", image: require("../assets/assets/architect.jpg") },
      { id: 819, name: "VETERINARIAN", image: require("../assets/assets/vet.jpg") },
      { id: 820, name: "ASTRONAUT", image: require("../assets/assets/astronaut.jpg") },
      { id: 821, name: "JOURNALIST", image: require("../assets/assets/journalist.jpg") },
      { id: 822, name: "ACCOUNTANT", image: require("../assets/assets/accountant.jpg") },
      { id: 823, name: "CARPENTER", image: require("../assets/assets/carpenter.jpg") },
      { id: 824, name: "PLUMBER", image: require("../assets/assets/plumber.jpg") },
      { id: 825, name: "ELECTRICIAN", image: require("../assets/assets/electrician.jpg") },
      { id: 826, name: "SOLDIER", image: require("../assets/assets/soldier.jpg") },
      { id: 827, name: "WRITER", image: require("../assets/assets/writer.jpg") },
      { id: 828, name: "MUSICIAN", image: require("../assets/assets/musician.jpg") },
      { id: 829, name: "DANCER", image: require("../assets/assets/dancer.jpg") },
      { id: 830, name: "BANKER", image: require("../assets/assets/banker.jpg") },
      { id: 831, name: "DESIGNER", image: require("../assets/assets/designer.jpg") },
      { id: 832, name: "FLORIST", image: require("../assets/assets/florist.jpg") },
      { id: 833, name: "LIBRARIAN", image: require("../assets/assets/librarian.jpg") },
      { id: 834, name: "TRAINER", image: require("../assets/assets/trainer.jpg") },
      { id: 835, name: "BARTENDER", image: require("../assets/assets/bartender.jpg") },
      { id: 836, name: "PSYCHOLOGIST", image: require("../assets/assets/psychologist.jpg") },
      { id: 837, name: "GEOLOGIST", image: require("../assets/assets/geologist.jpg") },
      { id: 838, name: "WELDER", image: require("../assets/assets/welder.jpg") },
      { id: 839, name: "DRIVER", image: require("../assets/assets/driver.jpg") },
      { id: 840, name: "TRANSLATOR", image: require("../assets/assets/translator.jpg") }
    ]
  }
];