export const missionsData = [
  {
    category: "Animals",
    items: [
      { id: 1, name: "DOG", image: require("../assets/assets/dog.jpg") },
      { id: 2, name: "CAT", image: require("../assets/assets/cat.jpg") },
      { id: 3, name: "FROG", image: require("../assets/assets/frog.jpg") },
      { id: 4, name: "LION", image: require("../assets/assets/lion.jpg") },
      { id: 5, name: "BEAR", image: require("../assets/assets/bear.jpg") },
      { id: 6, name: "HORSE", image: require("../assets/assets/horse.jpg") },
      { id: 7, name: "EAGLE", image: require("../assets/assets/eagle.jpg") },
      { id: 8, name: "RABBIT", image: require("../assets/assets/rabbit.jpg") },
      { id: 9, name: "WOLF", image: require("../assets/assets/wolf.jpg") },
      { id: 10, name: "KANGAROO", image: require("../assets/assets/kangaroo.jpg") },
      { id: 11, name: "PENGUIN", image: require("../assets/assets/penguin.jpg") },
      { id: 12, name: "CROCODILE", image: require("../assets/assets/crocodile.jpg") },
      { id: 13, name: "CHAMELEON", image: require("../assets/assets/chameleon.jpg") },
      { id: 14, name: "HIPPOPOTAMUS", image: require("../assets/assets/hippo.jpg") },
      { id: 15, name: "PORCUPINE", image: require("../assets/assets/porcupine.jpg") },
      { id: 16, name: "RHINOCEROS", image: require("../assets/assets/rhino.jpg") },
      { id: 17, name: "FLAMINGO", image: require("../assets/assets/flamingo.jpg") },
      { id: 18, name: "HEDGEHOG", image: require("../assets/assets/hedgehog.jpg") },
      { id: 19, name: "WOODPECKER", image: require("../assets/assets/woodpecker.jpg") },
      { id: 20, name: "HIPPOGRIFF", image: require("../assets/assets/hippogriff.jpg") },
    ],
  },
  {
    category: "Technology",
    items: [
      { id: 21, name: "PHONE", image: require("../assets/assets/phone.jpg") },
      { id: 22, name: "LAPTOP", image: require("../assets/assets/laptop.jpg") },
      { id: 23, name: "TABLET", image: require("../assets/assets/tablet.jpg") },
      { id: 24, name: "ROBOT", image: require("../assets/assets/robot.jpg") },
      { id: 25, name: "CAMERA", image: require("../assets/assets/camera.jpg") },
      { id: 26, name: "DRONE", image: require("../assets/assets/drone.jpg") },
      { id: 27, name: "PRINTER", image: require("../assets/assets/printer.jpg") },
      { id: 28, name: "MICROWAVE", image: require("../assets/assets/microwave.jpg") },
      { id: 29, name: "SPEAKER", image: require("../assets/assets/speaker.jpg") },
      { id: 210, name: "MONITOR", image: require("../assets/assets/monitor.jpg") },
      { id: 211, name: "HEADPHONES", image: require("../assets/assets/headphones.jpg") },
      { id: 212, name: "SMARTWATCH", image: require("../assets/assets/watch.jpg") },
      { id: 213, name: "PROJECTOR", image: require("../assets/assets/projector.jpg") },
      { id: 214, name: "TELEVISION", image: require("../assets/assets/tv.jpg") },
      { id: 215, name: "JOYSTICK", image: require("../assets/assets/joystick.jpg") },
      { id: 216, name: "SATELLITE", image: require("../assets/assets/satellite.jpg") },
      { id: 217, name: "MICROCHIP", image: require("../assets/assets/chip.jpg") },
      { id: 218, name: "CIRCUIT", image: require("../assets/assets/circuit.jpg") },
      { id: 219, name: "NANOTECH", image: require("../assets/assets/nano.jpg") },
      { id: 220, name: "QUANTUMCOMPUTER", image: require("../assets/assets/quantum.jpg") },
    ],
  },
  {
    category: "Kitchen Items",
    items: [
      { id: 31, name: "FORK", image: require("../assets/assets/fork.jpg") },
      { id: 32, name: "SPOON", image: require("../assets/assets/spoon.jpg") },
      { id: 33, name: "KNIFE", image: require("../assets/assets/knife.jpg") },
      { id: 34, name: "PLATE", image: require("../assets/assets/plate.jpg") },
      { id: 35, name: "CUP", image: require("../assets/assets/cup.jpg") },
      { id: 36, name: "BOWL", image: require("../assets/assets/bowl.jpg") },
      { id: 37, name: "POT", image: require("../assets/assets/pot.jpg") },
      { id: 38, name: "PAN", image: require("../assets/assets/pan.jpg") },
      { id: 39, name: "KETTLE", image: require("../assets/assets/kettle.jpg") },
      { id: 310, name: "BLENDER", image: require("../assets/assets/blender.jpg") },
      { id: 311, name: "TOASTER", image: require("../assets/assets/toaster.jpg") },
      { id: 312, name: "GRATER", image: require("../assets/assets/grater.jpg") },
      { id: 313, name: "STRAINER", image: require("../assets/assets/strainer.jpg") },
      { id: 314, name: "WHISK", image: require("../assets/assets/whisk.jpg") },
      { id: 315, name: "CUTTINGBOARD", image: require("../assets/assets/cuttingboard.jpg") },
      { id: 316, name: "MEASURINGCUP", image: require("../assets/assets/measuringcup.jpg") },
      { id: 317, name: "ROLLINGPIN", image: require("../assets/assets/rollingpin.jpg") },
      { id: 318, name: "MICROWAVE", image: require("../assets/assets/microwave.jpg") },
      { id: 319, name: "DISHWASHER", image: require("../assets/assets/dishwasher.jpg") },
      { id: 320, name: "PRESSURECOOKER", image: require("../assets/assets/pressurecooker.jpg") },
    ],
  },
  {
    category: "Fruits",
    items: [
      { id: 41, name: "APPLE", image: require("../assets/assets/apple.jpg") },
      { id: 42, name: "PEAR", image: require("../assets/assets/pear.jpg") },
      { id: 43, name: "BANANA", image: require("../assets/assets/banana.jpg") },
      { id: 44, name: "ORANGE", image: require("../assets/assets/orange.jpg") },
      { id: 45, name: "KIWI", image: require("../assets/assets/kiwi.jpg") },
      { id: 46, name: "GRAPE", image: require("../assets/assets/grape.jpg") },
      { id: 47, name: "MANGO", image: require("../assets/assets/mango.jpg") },
      { id: 48, name: "CHERRY", image: require("../assets/assets/cherry.jpg") },
      { id: 49, name: "PLUM", image: require("../assets/assets/plum.jpg") },
      { id: 410, name: "LEMON", image: require("../assets/assets/lemon.jpg") },
      { id: 411, name: "LIME", image: require("../assets/assets/lime.jpg") },
      { id: 412, name: "FIG", image: require("../assets/assets/fig.jpg") },
      { id: 413, name: "COCONUT", image: require("../assets/assets/coconut.jpg") },
      { id: 414, name: "PAPAYA", image: require("../assets/assets/papaya.jpg") },
      { id: 415, name: "PINEAPPLE", image: require("../assets/assets/pineapple.jpg") },
      { id: 416, name: "WATERMELON", image: require("../assets/assets/watermelon.jpg") },
      { id: 417, name: "STRAWBERRY", image: require("../assets/assets/strawberry.jpg") },
      { id: 418, name: "BLUEBERRY", image: require("../assets/assets/blueberry.jpg") },
      { id: 419, name: "BLACKBERRY", image: require("../assets/assets/blackberry.jpg") },
      { id: 420, name: "POMEGRANATE", image: require("../assets/assets/pomegranate.jpg") },
    ],
  },
  {
    category: "Countries",
    items: [
      { id: 51, name: "USA", image: require("../assets/assets/usa.jpg") },
      { id: 52, name: "FRANCE", image: require("../assets/assets/france.jpg") },
      { id: 53, name: "JAPAN", image: require("../assets/assets/japan.jpg") },
      { id: 54, name: "BRAZIL", image: require("../assets/assets/brazil.jpg") },
      { id: 55, name: "INDIA", image: require("../assets/assets/india.jpg") },
      { id: 56, name: "ITALY", image: require("../assets/assets/italy.jpg") },
      { id: 57, name: "CANADA", image: require("../assets/assets/canada.jpg") },
      { id: 58, name: "SPAIN", image: require("../assets/assets/spain.jpg") },
      { id: 59, name: "GERMANY", image: require("../assets/assets/germany.jpg") },
      { id: 510, name: "RUSSIA", image: require("../assets/assets/russia.jpg") },
      { id: 511, name: "MEXICO", image: require("../assets/assets/mexico.jpg") },
      { id: 512, name: "CHINA", image: require("../assets/assets/china.jpg") },
      { id: 513, name: "EGYPT", image: require("../assets/assets/egypt.jpg") },
      { id: 514, name: "NIGERIA", image: require("../assets/assets/nigeria.jpg") },
      { id: 515, name: "NORWAY", image: require("../assets/assets/norway.jpg") },
      { id: 516, name: "ARGENTINA", image: require("../assets/assets/argentina.jpg") },
      { id: 517, name: "TURKEY", image: require("../assets/assets/turkey.jpg") },
      { id: 518, name: "POLAND", image: require("../assets/assets/poland.jpg") },
      { id: 519, name: "PORTUGAL", image: require("../assets/assets/portugal.jpg") },
      { id: 520, name: "AUSTRALIA", image: require("../assets/assets/australia.jpg") },
    ],
  },
  {
    category: "Sports",
    items: [
      { id: 61, name: "SOCCER", image: require("../assets/assets/soccer.jpg") },
      { id: 62, name: "BASKETBALL", image: require("../assets/assets/basketball.jpg") },
      { id: 63, name: "TENNIS", image: require("../assets/assets/tennis.jpg") },
      { id: 64, name: "CRICKET", image: require("../assets/assets/cricket.jpg") },
      { id: 65, name: "BASEBALL", image: require("../assets/assets/baseball.jpg") },
      { id: 66, name: "RUGBY", image: require("../assets/assets/rugby.jpg") },
      { id: 67, name: "SWIMMING", image: require("../assets/assets/swimming.jpg") },
      { id: 68, name: "BOXING", image: require("../assets/assets/boxing.jpg") },
      { id: 69, name: "VOLLEYBALL", image: require("../assets/assets/volleyball.jpg") },
      { id: 610, name: "GOLF", image: require("../assets/assets/golf.jpg") },
      { id: 611, name: "HOCKEY", image: require("../assets/assets/hockey.jpg") },
      { id: 612, name: "ARCHERY", image: require("../assets/assets/archery.jpg") },
      { id: 613, name: "FENCING", image: require("../assets/assets/fencing.jpg") },
      { id: 614, name: "SKIING", image: require("../assets/assets/skiing.jpg") },
      { id: 615, name: "SURFING", image: require("../assets/assets/surfing.jpg") },
      { id: 616, name: "CYCLING", image: require("../assets/assets/cycling.jpg") },
      { id: 617, name: "SKATEBOARD", image: require("../assets/assets/skateboard.jpg") },
      { id: 618, name: "WEIGHTLIFTING", image: require("../assets/assets/weightlifting.jpg") },
      { id: 619, name: "TAEKWONDO", image: require("../assets/assets/taekwondo.jpg") },
      { id: 620, name: "MARTIALARTS", image: require("../assets/assets/martialarts.jpg") },
    ],
  },
  {
    category: "Transportation",
    items: [
      { id: 71, name: "CAR", image: require("../assets/assets/car.jpg") },
      { id: 72, name: "BIKE", image: require("../assets/assets/bike.jpg") },
      { id: 73, name: "BUS", image: require("../assets/assets/bus.jpg") },
      { id: 74, name: "TRAIN", image: require("../assets/assets/train.jpg") },
      { id: 75, name: "SHIP", image: require("../assets/assets/ship.jpg") },
      { id: 76, name: "PLANE", image: require("../assets/assets/plane.jpg") },
      { id: 77, name: "SUBWAY", image: require("../assets/assets/subway.jpg") },
      { id: 78, name: "HELICOPTER", image: require("../assets/assets/helicopter.jpg") },
      { id: 79, name: "SCOOTER", image: require("../assets/assets/scooter.jpg") },
      { id: 710, name: "BALLOON", image: require("../assets/assets/balloon.jpg") },
      { id: 711, name: "TRACTOR", image: require("../assets/assets/tractor.jpg") },
      { id: 712, name: "AMBULANCE", image: require("../assets/assets/ambulance.jpg") },
      { id: 713, name: "FIRETRUCK", image: require("../assets/assets/firetruck.jpg") },
      { id: 714, name: "ROCKET", image: require("../assets/assets/rocket.jpg") },
      { id: 715, name: "CABLECAR", image: require("../assets/assets/cablecar.jpg") },
      { id: 716, name: "FERRY", image: require("../assets/assets/ferry.jpg") },
      { id: 717, name: "YACHT", image: require("../assets/assets/yacht.jpg") },
      { id: 718, name: "SPACECRAFT", image: require("../assets/assets/spacecraft.jpg") },
      { id: 719, name: "MONORAIL", image: require("../assets/assets/monorail.jpg") },
      { id: 720, name: "DIRIGIBLE", image: require("../assets/assets/dirigible.jpg") },
    ],
  },
  {
    category: "Professions",
    items: [
      { id: 81, name: "DOCTOR", image: require("../assets/assets/doctor.jpg") },
      { id: 82, name: "TEACHER", image: require("../assets/assets/teacher.jpg") },
      { id: 83, name: "FARMER", image: require("../assets/assets/farmer.jpg") },
      { id: 84, name: "CHEF", image: require("../assets/assets/chef.jpg") },
      { id: 85, name: "POLICE", image: require("../assets/assets/police.jpg") },
      { id: 86, name: "FIREFIGHTER", image: require("../assets/assets/firefighter.jpg") },
      { id: 87, name: "ENGINEER", image: require("../assets/assets/engineer.jpg") },
      { id: 88, name: "SCIENTIST", image: require("../assets/assets/scientist.jpg") },
      { id: 89, name: "ACTOR", image: require("../assets/assets/actor.jpg") },
      { id: 810, name: "LAWYER", image: require("../assets/assets/lawyer.jpg") },
      { id: 811, name: "NURSE", image: require("../assets/assets/nurse.jpg") },
      { id: 812, name: "MECHANIC", image: require("../assets/assets/mechanic.jpg") },
      { id: 813, name: "PILOT", image: require("../assets/assets/pilot.jpg") },
      { id: 814, name: "ARTIST", image: require("../assets/assets/artist.jpg") },
      { id: 815, name: "PHOTOGRAPHER", image: require("../assets/assets/photographer.jpg") },
      { id: 816, name: "DENTIST", image: require("../assets/assets/dentist.jpg") },
      { id: 817, name: "PROGRAMMER", image: require("../assets/assets/programmer.jpg") },
      { id: 818, name: "ARCHITECT", image: require("../assets/assets/architect.jpg") },
      { id: 819, name: "VETERINARIAN", image: require("../assets/assets/vet.jpg") },
      { id: 820, name: "ASTRONAUT", image: require("../assets/assets/astronaut.jpg")}
    ]
}]